environment:
  matrix:
    - TARGET: MINGW64
    - TARGET: MINGW32
  GAUCHE_INFO_URL: https://practical-scheme.net/gauche/releases
  GAUCHE_INSTALLER_URL: https://prdownloads.sourceforge.net/gauche

for:
  -
    matrix:
      only:
        - TARGET: MINGW64
    environment:
      MSYSTEM: MINGW64
      PATH: C:\msys64\mingw64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\bin;%PATH%
      GAUCHE_INSTALLER_BIT: 64bit
      GAUCHE_PATH: C:\Program Files\Gauche\bin
      RESULT_ZIP: Gauche-x86_64.zip
      RESULT_PATH: ..\Gauche-mingw-dist\Gauche-x86_64
  -
    matrix:
      only:
        - TARGET: MINGW32
    environment:
      MSYSTEM: MINGW32
      PATH: C:\msys64\mingw32\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\bin;%PATH%
      GAUCHE_INSTALLER_BIT: 32bit
      GAUCHE_PATH: C:\Program Files (x86)\Gauche\bin
      RESULT_ZIP: Gauche-i686.zip
      RESULT_PATH: ..\Gauche-mingw-dist\Gauche-i686

install:
#  - echo %TARGET%
#  - echo %MSYSTEM%
#  - echo %PATH%
  - cd
  - for /f "usebackq delims=" %%i in (`curl -f %GAUCHE_INFO_URL%/latest.txt 2^>nul`) do set GAUCHE_INSTALLER_VERSION=%%i
  - echo %GAUCHE_INSTALLER_VERSION%
  - set GAUCHE_INSTALLER=Gauche-mingw-%GAUCHE_INSTALLER_VERSION%-%GAUCHE_INSTALLER_BIT%.msi
  - echo %GAUCHE_INSTALLER%
  - curl -f -L --progress-bar -o %GAUCHE_INSTALLER% %GAUCHE_INSTALLER_URL%/%GAUCHE_INSTALLER%
  - msiexec /i %GAUCHE_INSTALLER% /quiet /qn /norestart
  - set PATH=%PATH%;%GAUCHE_PATH%
#  - echo %PATH%
  - gosh -V
  - bash -lc "pacman -S --noconfirm msys/winpty"
  - bash -lc "winpty --version"
  - bash -lc "where openssl"
  - bash -lc "openssl version"

build_script:
  - bash -lc "pwd"
  - bash -lc "echo $APPVEYOR_BUILD_FOLDER"
  - bash -lc "gcc -v"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && ./DIST gen"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && src/mingw-dist.sh"

after_build:
  - 7z a %RESULT_ZIP% %RESULT_PATH%

test_script:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && make check"

artifacts:
  - path: Gauche-*.zip
#  - path: ext/tls/kick_openssl.sh
#  - path: ext/tls/ssltest.log

