;; Generated automatically from Unicode character database 
;; See src/gen-unicode.scm for the description of data structures. 
;; Unicode version 13.0.0.  Do not edit. 
(define-constant GB_CR 0)
(define-constant GB_LF 1)
(define-constant GB_Control 2)
(define-constant GB_Extend 3)
(define-constant GB_ZWJ 4)
(define-constant GB_Regional_Indicator 5)
(define-constant GB_Prepend 6)
(define-constant GB_SpacingMark 7)
(define-constant GB_L 8)
(define-constant GB_V 9)
(define-constant GB_T 10)
(define-constant GB_LV 11)
(define-constant GB_LVT 12)
(define-constant GB_ExtPict 13)
(define-constant GB_Other 14)
(define-constant
 *GB-properties*
 '((CR . 0) (LF . 1) (Control . 2) (Extend . 3) (ZWJ . 4)
   (Regional_Indicator . 5) (Prepend . 6) (SpacingMark . 7) (L . 8) (V . 9)
   (T . 10) (LV . 11) (LVT . 12) (ExtPict . 13) (Other . 14)))
(define-constant WB_CR 0)
(define-constant WB_LF 1)
(define-constant WB_Newline 2)
(define-constant WB_Extend 3)
(define-constant WB_ZWJ 4)
(define-constant WB_Regional_Indicator 5)
(define-constant WB_Format 6)
(define-constant WB_Katakana 7)
(define-constant WB_Hebrew_Letter 8)
(define-constant WB_ALetter 9)
(define-constant WB_Single_Quote 10)
(define-constant WB_Double_Quote 11)
(define-constant WB_MidLetter 12)
(define-constant WB_MidNum 13)
(define-constant WB_MidNumLet 14)
(define-constant WB_Numeric 15)
(define-constant WB_ExtendNumLet 16)
(define-constant WB_WSegSpace 17)
(define-constant WB_ExtPict 18)
(define-constant WB_ExtPict_ALetter 19)
(define-constant WB_Other 20)
(define-constant
 *WB-properties*
 '((CR . 0) (LF . 1) (Newline . 2) (Extend . 3) (ZWJ . 4)
   (Regional_Indicator . 5) (Format . 6) (Katakana . 7) (Hebrew_Letter . 8)
   (ALetter . 9) (Single_Quote . 10) (Double_Quote . 11) (MidLetter . 12)
   (MidNum . 13) (MidNumLet . 14) (Numeric . 15) (ExtendNumLet . 16)
   (WSegSpace . 17) (ExtPict . 18) (ExtPict_ALetter . 19) (Other . 20)))
